<?php

namespace Tests\Unit;

use App\Models\ShortUrl;
use App\Services\UrlShortenerService;
use Illuminate\Foundation\Testing\RefreshDatabase;
// use PHPUnit\Framework\TestCase;
use Tests\TestCase;

class UrlShortenerServiceTest extends TestCase
{
    use RefreshDatabase;

    private UrlShortenerService $urlShortenerService;

    protected function setUp(): void
    {
        parent::setUp();
        // $this->urlShortenerService = new UrlShortenerService();
        $this->urlShortenerService = app(UrlShortenerService::class);
    }

    public function testItCreatesShortUrlWithCustomSlug(): void
    {
        $shortUrl = $this->urlShortenerService->createShortUrl(
            'https://example.com',
            'custom-slug'
        );

        $this->assertEquals('https://example.com', $shortUrl->original_url);
        $this->assertEquals('custom-slug', $shortUrl->slug);
        $this->assertNull($shortUrl->expires_at);
    }

    public function testItCreatesShortUrlWithAutoGeneratedSlug(): void
    {
        $shortUrl = $this->urlShortenerService->createShortUrl('https://example.com');

        $this->assertEquals('https://example.com', $shortUrl->original_url);
        $this->assertNotNull($shortUrl->slug);
        $this->assertNull($shortUrl->expires_at);
    }

    public function testItCreatesShortUrlWithExpiration(): void
    {
        $expiresAt = now()->addDay();
        $shortUrl = $this->urlShortenerService->createShortUrl(
            'https://example.com',
            null,
            $expiresAt
        );

        $this->assertEquals('https://example.com', $shortUrl->original_url);
        $this->assertEquals($expiresAt->toDateTimeString(), $shortUrl->expires_at->toDateTimeString());
    }

    public function testItFindsUrlBySlug(): void
    {
        $shortUrl = ShortUrl::factory()->create(
            [
            'original_url' => 'https://example.com',
            'slug' => 'test-slug',
            ]
        );

        $foundUrl = $this->urlShortenerService->findBySlug('test-slug');

        $this->assertNotNull($foundUrl);
        $this->assertEquals($shortUrl->id, $foundUrl->id);
    }

    public function testItReturnsNullForNonexistentSlug(): void
    {
        $foundUrl = $this->urlShortenerService->findBySlug('nonexistent-slug');

        $this->assertNull($foundUrl);
    }
}
